#!/usr/bin/env node
/**
 * PROJECT INITIALIZATION - /init COMMAND
 * Version: 1.0 | Devin Pattern Integration
 * 
 * LSP-first project analysis with deep repository understanding
 * Creates AGENTS.md, todo.md, and environment verification.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// ============================================================================
// CONFIGURATION
// ============================================================================

const CLAUDE_DIR = path.join(process.env.HOME, '.claude');

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

function log(message, type = 'info') {
  const timestamp = new Date().toISOString().split('T')[1].split('.')[0];
  const prefix = {
    'info': '🔵',
    'warn': '🟡',
    'error': '🔴',
    'success': '✅'
  }[type] || 'ℹ️';
  
  console.log(`${prefix} [${timestamp}] ${message}`);
}

function ensureDirectory(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    log(`Created: ${dir}`, 'success');
  }
}

function createFile(filePath, content, description) {
  try {
    fs.writeFileSync(filePath, content, 'utf8');
    log(`✓ ${description}`, 'success');
    return true;
  } catch (error) {
    log(`✗ ${description}: ${error.message}`, 'error');
    return false;
  }
}

function findProjectRoot() {
  let cwd = process.cwd();
  while (cwd !== '/' && cwd !== process.env.HOME) {
    if (fs.existsSync(path.join(cwd, '.git')) || 
        fs.existsSync(path.join(cwd, 'package.json')) ||
        fs.existsSync(path.join(cwd, '.claude'))) {
      return cwd;
    }
    cwd = path.dirname(cwd);
  }
  return process.cwd();
}

function scanProjectStructure(root) {
  const structure = {
    files: [],
    directories: [],
    packageJson: null,
    gitRepo: false,
    techStack: []
  };
  
  try {
    // Check for package.json
    const packagePath = path.join(root, 'package.json');
    if (fs.existsSync(packagePath)) {
      structure.packageJson = JSON.parse(fs.readFileSync(packagePath, 'utf8'));
      structure.techStack.push('Node.js');
    }
    
    // Check for git
    if (fs.existsSync(path.join(root, '.git'))) {
      structure.gitRepo = true;
    }
    
    // Scan top-level structure
    const items = fs.readdirSync(root);
    for (const item of items) {
      if (item.startsWith('.') || item === 'node_modules' || item === 'dist' || item === 'build') {
        continue;
      }
      
      const fullPath = path.join(root, item);
      if (fs.statSync(fullPath).isDirectory()) {
        structure.directories.push(item);
        
        // Detect tech stack from directories
        if (item === 'src' || item === 'app' || item === 'pages') structure.techStack.push('Source Directory');
        if (item === 'public' || item === 'static') structure.techStack.push('Static Assets');
        if (item === 'tests' || item === '__tests__') structure.techStack.push('Testing');
        if (item === 'docs') structure.techStack.push('Documentation');
      } else {
        structure.files.push(item);
        
        // Detect tech stack from files
        if (item.endsWith('.ts') || item.endsWith('.tsx')) structure.techStack.push('TypeScript');
        if (item.endsWith('.py')) structure.techStack.push('Python');
        if (item.endsWith('.java')) structure.techStack.push('Java');
        if (item === 'requirements.txt') structure.techStack.push('Python Dependencies');
        if (item === 'Dockerfile') structure.techStack.push('Docker');
        if (item === 'docker-compose.yml') structure.techStack.push('Docker Compose');
      }
    }
    
    structure.techStack = [...new Set(structure.techStack)];
    return structure;
  } catch (error) {
    log(`⚠️ Error scanning structure: ${error.message}`, 'warn');
    return structure;
  }
}

// ============================================================================
// STEP 1: CREATE AGENTS.MD (CURSOR PATTERN)
// ============================================================================

function createAgentsMd(root, structure) {
  log('Creating AGENTS.md (Cursor auto-context)...', 'info');
  
  const content = `# AGENTS.md - Repository Knowledge
**Auto-generated by /init** | **Last Updated:** ${new Date().toISOString().split('T')[0]}

## 📋 Project Overview
**Root:** ${root}
**Git:** ${structure.gitRepo ? '✅ Yes' : '❌ No'}
**Package Manager:** ${structure.packageJson ? 'detected' : 'none detected'}

## 🏗️ Structure
\`\`\`
${root}/
${structure.directories.length > 0 ? structure.directories.map(d => `├── ${d}/`).join('\n') : '├── (empty)'}
${structure.files.length > 0 ? structure.files.map(f => `├── ${f}`).join('\n') : ''}
\`\`\`

## 🛠️ Tech Stack
${structure.techStack.length > 0 ? structure.techStack.map(t => `- ${t}`).join('\n') : '- Not detected'}

## 📦 Dependencies
${structure.packageJson ? `
\`\`\`json
${JSON.stringify(structure.packageJson.dependencies || {}, null, 2)}
\`\`\`
` : '- No package.json found'}

## 🎯 Known Patterns
${structure.directories.includes('src') ? '- Source directory: src/' : ''}
${structure.directories.includes('tests') || structure.directories.includes('__tests__') ? '- Test directory found' : ''}
${structure.files.some(f => f.endsWith('.test.js') || f.endsWith('.spec.js')) ? '- Test files present' : ''}

## 🔧 Development Commands
\`\`\`bash
# Standard commands
npm install    # Install dependencies
npm run dev    # Development server
npm run build  # Build for production
npm test       # Run tests
\`\`\`

## 🤖 Agent Instructions
- Use LSP for code exploration
- Never modify existing test files
- Check this file for project context
- Follow detected tech stack patterns
- Update this file when structure changes

---
*Auto-updated by Claude Code /init command*
`;

  const agentsPath = path.join(root, '.claude', 'AGENTS.md');
  ensureDirectory(path.join(root, '.claude'));
  return createFile(agentsPath, content, 'AGENTS.md');
}

// ============================================================================
// STEP 2: CREATE TODO.MD (MANUS PATTERN)
// ============================================================================

function createTodoMd(root, structure) {
  log('Creating todo.md (Manus task management)...', 'info');
  
  const content = `# TODO.md - Task Queue
**Central task hub** | **Auto-generated by /init** | **${new Date().toISOString().split('T')[0]}**

## 🎯 Current Tasks
- [ ] **Setup Complete**: Run /start to sync all configs
- [ ] **Environment Check**: Verify MCP servers are configured
- [ ] **First Task**: Define your first development task

## 📋 Task Queue
\`\`\`
1. Analysis Phase
   └─ Research requirements
   └─ Identify dependencies
   └─ Plan architecture

2. Planning Phase
   └─ Break down tasks
   └─ Create numbered steps
   └─ Update this file

3. Implementation
   └─ Execute tasks
   └─ Update todo.md
   └─ Test each step

4. Review
   └─ Check quality
   └─ Update knowledge
   └─ Deploy
\`\`\`

## 📊 Progress Tracking
**Total Tasks:** 4  
**Completed:** 0  
**In Progress:** 0  
**Success Rate:** 0%

## 🧠 Knowledge Module
**Session Context:** Fresh initialization  
**Last Update:** ${new Date().toISOString()}  
**Active Frameworks:** None yet  

## 🔄 Event Log
${new Date().toISOString()} - Project initialized with /init  
${new Date().toISOString()} - AGENTS.md created  
${new Date().toISOString()} - Todo.md created  

## 📝 Quick Actions
- Add task: "- [ ] Task description"
- Complete task: "- [x] Task description"
- Add note: "Note: Your note here"

---
*Use this file to track all project tasks*
*Update after every significant change*
`;

  const todoPath = path.join(root, '.claude', 'todo.md');
  ensureDirectory(path.join(root, '.claude'));
  return createFile(todoPath, content, 'todo.md');
}

// ============================================================================
// STEP 3: ENVIRONMENT VERIFICATION (AMP PATTERN)
// ============================================================================

function verifyEnvironment(root) {
  log('Verifying environment (Amp concision)...', 'info');
  
  const checks = [];
  
  // Check Node.js
  try {
    const nodeVersion = execSync('node --version', { encoding: 'utf8' }).trim();
    checks.push({ name: 'Node.js', status: '✅', detail: nodeVersion });
  } catch {
    checks.push({ name: 'Node.js', status: '❌', detail: 'Not found' });
  }
  
  // Check npm
  try {
    const npmVersion = execSync('npm --version', { encoding: 'utf8' }).trim();
    checks.push({ name: 'npm', status: '✅', detail: npmVersion });
  } catch {
    checks.push({ name: 'npm', status: '❌', detail: 'Not found' });
  }
  
  // Check git
  try {
    const gitVersion = execSync('git --version', { encoding: 'utf8' }).trim();
    checks.push({ name: 'Git', status: '✅', detail: gitVersion });
  } catch {
    checks.push({ name: 'Git', status: '⚠️', detail: 'Optional' });
  }
  
  // Check .claude directory
  const claudeExists = fs.existsSync(path.join(root, '.claude'));
  checks.push({ name: '.claude', status: claudeExists ? '✅' : '❌', detail: 'Config dir' });
  
  // Check package.json
  const pkgExists = fs.existsSync(path.join(root, 'package.json'));
  checks.push({ name: 'package.json', status: pkgExists ? '✅' : '⚠️', detail: 'Project file' });
  
  // Log results (4-line concision)
  log('\n--- Environment Check (4-line summary) ---', 'info');
  checks.forEach(check => {
    log(`${check.status} ${check.name}: ${check.detail}`, 'info');
  });
  
  const allGood = checks.filter(c => c.status === '✅').length >= 2;
  return allGood;
}

// ============================================================================
// STEP 4: CREATE PROJECT KNOWLEDGE (MANUS PATTERN)
// ============================================================================

function createProjectKnowledge(root, structure) {
  log('Creating PROJECT_KNOWLEDGE.md...', 'info');
  
  const content = `# PROJECT_KNOWLEDGE.md
**Persistent Context Storage** | **Manus Pattern** | **${new Date().toISOString().split('T')[0]}**

## 🎯 Project Identity
**Name:** ${path.basename(root)}
**Root:** ${root}
**Initialized:** ${new Date().toISOString()}

## 🏗️ Architecture Snapshot
\`\`\`
${structure.directories.length > 0 ? structure.directories.join(', ') : 'Empty'}
\`\`\`

## 🧩 Component Registry
${structure.files.filter(f => f.match(/\.(js|ts|jsx|tsx)$/)).map(f => `- ${f}`).join('\n') || '- No components yet'}

## 🔗 Dependencies
${structure.packageJson ? Object.keys(structure.packageJson.dependencies || {}).map(d => `- ${d}`).join('\n') : '- None detected'}

## 📚 Documentation Links
- [AGENTS.md](./AGENTS.md) - Repository context
- [todo.md](./todo.md) - Task management
- [CLAUDE.md](./CLAUDE.md) - Global config

## 🎨 Design Patterns
${structure.techStack.includes('TypeScript') ? '- TypeScript: Strong typing' : ''}
${structure.techStack.includes('React') ? '- React: Component architecture' : ''}
${structure.techStack.includes('Node.js') ? '- Node.js: Backend runtime' : ''}

## 📊 Metrics
**Files:** ${structure.files.length}
**Directories:** ${structure.directories.length}
**Tech Stack Items:** ${structure.techStack.length}

## 🔄 Update Log
${new Date().toISOString()} - Initial knowledge base created

---
*This file persists across sessions*
*Update after major architectural changes*
`;

  const knowledgePath = path.join(root, '.claude', 'PROJECT_KNOWLEDGE.md');
  ensureDirectory(path.join(root, '.claude'));
  return createFile(knowledgePath, content, 'PROJECT_KNOWLEDGE.md');
}

// ============================================================================
// STEP 5: CREATE CONDUCTOR WORKFLOW (MANUS EVENT LOOP)
// ============================================================================

function createConductorWorkflow(root) {
  log('Creating CONDUCTOR_WORKFLOW.json...', 'info');
  
  const workflow = {
    name: `${path.basename(root)}-workflow`,
    version: "1.0",
    description: "Auto-generated workflow for project initialization",
    phases: [
      {
        name: "Initialization",
        tasks: [
          { name: "Sync configs", script: "config-sync.js", status: "pending" },
          { name: "Verify environment", script: "init-project.js", status: "completed" },
          { name: "Create knowledge base", script: "init-project.js", status: "completed" }
        ]
      },
      {
        name: "Analysis",
        tasks: [
          { name: "Code exploration", method: "LSP-first", status: "pending" },
          { name: "Pattern detection", method: "AGENTS.md", status: "pending" }
        ]
      },
      {
        name: "Planning",
        tasks: [
          { name: "Task breakdown", method: "numbered steps", status: "pending" },
          { name: "Todo.md update", method: "Manus pattern", status: "pending" }
        ]
      }
    ],
    triggers: ["Baue", "Fix", "Create", "Entwickle", "Master Loop für"],
    metrics: {
      taskCompletionRate: 0,
      successRate: 0,
      lastUpdate: new Date().toISOString()
    }
  };
  
  const workflowPath = path.join(root, '.claude', 'CONDUCTOR_WORKFLOW.json');
  ensureDirectory(path.join(root, '.claude'));
  return createFile(workflowPath, JSON.stringify(workflow, null, 2), 'CONDUCTOR_WORKFLOW.json');
}

// ============================================================================
// MAIN EXECUTION
// ============================================================================

async function main() {
  log('═══════════════════════════════════════════════════════════', 'info');
  log('🔵 PROJECT INITIALIZATION - /init', 'info');
  log('═══════════════════════════════════════════════════════════', 'info');
  
  const root = findProjectRoot();
  log(`Project root: ${root}`, 'info');
  
  // LSP-first analysis (simulated)
  log('\n📍 Phase 1: LSP-based analysis...', 'info');
  const structure = scanProjectStructure(root);
  
  // Create all artifacts
  log('\n📍 Phase 2: Creating artifacts...', 'info');
  const results = {
    agents: createAgentsMd(root, structure),
    todo: createTodoMd(root, structure),
    knowledge: createProjectKnowledge(root, structure),
    workflow: createConductorWorkflow(root),
    environment: verifyEnvironment(root)
  };
  
  // Summary
  log('\n═══════════════════════════════════════════════════════════', 'info');
  log('📊 INITIALIZATION SUMMARY', 'info');
  log('═══════════════════════════════════════════════════════════', 'info');
  
  const allSuccess = Object.values(results).every(r => r === true);
  
  if (allSuccess) {
    log('✅ Project initialized successfully', 'success');
    log('\n📁 Created files:', 'info');
    log('   • .claude/AGENTS.md (Cursor auto-context)', 'info');
    log('   • .claude/todo.md (Manus task hub)', 'info');
    log('   • .claude/PROJECT_KNOWLEDGE.md (Persistent context)', 'info');
    log('   • .claude/CONDUCTOR_WORKFLOW.json (Event loop)', 'info');
    log('\n🎯 Next steps:', 'info');
    log('   1. Check .claude/todo.md for tasks', 'info');
    log('   2. Say "Baue X" to start Amp style', 'info');
    log('   3. Say "Master Loop für: X" for Devin planning', 'info');
  } else {
    log('⚠️ Some initialization steps failed', 'warn');
  }
  
  log('\n═══════════════════════════════════════════════════════════', 'info');
  
  return allSuccess;
}

// Execute
if (require.main === module) {
  main().catch(error => {
    console.error(`Fatal error: ${error.message}`);
    process.exit(1);
  });
}

module.exports = { main };