#!/usr/bin/env node
/**
 * BMAD INTEGRATION MODULE
 * Version: 1.0 | Best Practices Implementation
 *
 * Integrates BMAD (B-MAD Method) framework into Claude Code workflow
 * with automatic pattern detection and activation.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// ============================================================================
// CONFIGURATION
// ============================================================================

const CLAUDE_DIR = path.join(process.env.HOME, '.claude');
const EXECUTORS_DIR = path.join(CLAUDE_DIR, 'EXECUTORS');
const CONFIGS_DIR = path.join(CLAUDE_DIR, 'CONFIGS');
const PLUGINS_DIR = path.join(CLAUDE_DIR, 'PLUGINS');
const BMAD_DIR = path.join(PLUGINS_DIR, 'bmad');

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

function log(message, type = 'info') {
  const timestamp = new Date().toISOString().split('T')[1].split('.')[0];
  const prefix = {
    'info': '🟣',
    'warn': '🟡',
    'error': '🔴',
    'success': '✅'
  }[type] || 'ℹ️';

  console.log(`${prefix} [${timestamp}] ${message}`);
}

function ensureDirectory(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    log(`Created: ${dir}`, 'success');
  }
}

function createFile(filePath, content, description) {
  try {
    fs.writeFileSync(filePath, content, 'utf8');
    log(`✓ ${description}`, 'success');
    return true;
  } catch (error) {
    log(`✗ ${description}: ${error.message}`, 'error');
    return false;
  }
}

// ============================================================================
// STEP 1: CREATE BMAD METHOD DOCUMENTATION
// ============================================================================

function createBMADMethod() {
  log('Creating BMAD method documentation...', 'info');

  const methodLines = [
    '# BMAD Method - B-MAD Framework',
    '',
    '## Overview',
    'BMAD (B-MAD Method) is a comprehensive AI agent orchestration framework designed for systematic problem-solving and development workflows.',
    '',
    '## Core Principles',
    '',
    '### 1. B = Business/Breakdown',
    '**Purpose**: Understand the business context and break down requirements',
    '',
    '**Activities**:',
    '- Stakeholder analysis',
    '- Requirements gathering',
    '- Business logic validation',
    '- Success criteria definition',
    '',
    '**Output**: Business Requirements Document (BRD)',
    '',
    '### 2. M = Model/Map',
    '**Purpose**: Create technical models and architectural maps',
    '',
    '**Activities**:',
    '- System architecture design',
    '- Data model creation',
    '- API contract definition',
    '- Component mapping',
    '',
    '**Output**: Technical Specification Document (TSD)',
    '',
    '### 3. A = Architecture/Build',
    '**Purpose**: Implement the architecture and build components',
    '',
    '**Activities**:',
    '- Code scaffolding',
    '- Component implementation',
    '- Integration development',
    '- Testing setup',
    '',
    '**Output**: Functional Implementation',
    '',
    '### 4. D = Deploy/Deliver',
    '**Purpose**: Deploy and deliver the solution',
    '',
    '**Activities**:',
    '- Deployment orchestration',
    '- Quality assurance',
    '- Documentation',
    '- Handover',
    '',
    '**Output**: Production-ready solution',
    '',
    '## BMAD Workflow Phases',
    '',
    '### Phase 1: Business Analysis',
    '```',
    'Input: User Request',
    '↓',
    '[B] Business Context Analysis',
    '↓',
    'Requirements Breakdown',
    '↓',
    'Success Criteria',
    '↓',
    'Output: BRD',
    '```',
    '',
    '### Phase 2: Technical Modeling',
    '```',
    'Input: BRD',
    '↓',
    '[M] Model Architecture',
    '↓',
    'Data & API Mapping',
    '↓',
    'Component Design',
    '↓',
    'Output: TSD',
    '```',
    '',
    '### Phase 3: Architecture & Build',
    '```',
    'Input: TSD',
    '↓',
    '[A] Architecture Setup',
    '↓',
    'Component Implementation',
    '↓',
    'Integration & Testing',
    '↓',
    'Output: Working Code',
    '```',
    '',
    '### Phase 4: Deployment & Delivery',
    '```',
    'Input: Working Code',
    '↓',
    '[D] Deploy Orchestration',
    '↓',
    'Quality Verification',
    '↓',
    'Documentation & Handover',
    '↓',
    'Output: Production Solution',
    '```',
    '',
    '## BMAD in Claude Code',
    '',
    '### Auto-Detection Triggers',
    'BMAD activates when prompt contains:',
    '- "bmad" or "BMAD"',
    '- "business analysis"',
    '- "technical specification"',
    '- "architecture design"',
    '- "systematic development"',
    '- "methodical approach"',
    '- "business requirements"',
    '- "technical model"',
    '- "architecture build"',
    '- "deploy deliver"',
    '',
    '### Integration Pattern',
    'When BMAD is detected:',
    '1. **Phase 1**: Generate BRD with business analysis',
    '2. **Phase 2**: Create technical specification',
    '3. **Phase 3**: Implement architecture',
    '4. **Phase 4**: Deploy and document',
    '',
    '### Example Prompts',
    '```',
    '"Use BMAD method to build a login system"',
    '→ Generates: BRD → TSD → Implementation → Deployment',
    '',
    '"Business analysis for e-commerce platform"',
    '→ Triggers Phase 1: Business Analysis',
    '',
    '"Technical model for user authentication"',
    '→ Triggers Phase 2: Technical Modeling',
    '```',
    '',
    '## BMAD Templates',
    '',
    '### BRD Template',
    '```',
    '# Business Requirements Document',
    '',
    '## Executive Summary',
    '[What problem are we solving?]',
    '',
    '## Stakeholders',
    '[List key stakeholders]',
    '',
    '## Requirements',
    '### Functional',
    '- [Requirement 1]',
    '- [Requirement 2]',
    '',
    '### Non-Functional',
    '- [Performance]',
    '- [Security]',
    '- [Scalability]',
    '',
    '## Success Criteria',
    '- [Metric 1]',
    '- [Metric 2]',
    '',
    '## Constraints',
    '- [Technical]',
    '- [Business]',
    '- [Timeline]',
    '```',
    '',
    '### TSD Template',
    '```',
    '# Technical Specification Document',
    '',
    '## System Architecture',
    '[High-level architecture diagram]',
    '',
    '## Data Model',
    '[Entity relationship diagram]',
    '',
    '## API Contracts',
    '[Endpoint definitions]',
    '',
    '## Component Design',
    '[Component hierarchy]',
    '',
    '## Integration Points',
    '[External dependencies]',
    '',
    '## Testing Strategy',
    '[Unit, Integration, E2E]',
    '```',
    '',
    '## BMAD Best Practices',
    '',
    '1. **Systematic Approach**: Follow B→M→A→D sequence',
    '2. **Documentation First**: Create BRD before coding',
    '3. **Model Reality**: Ensure models match requirements',
    '4. **Build Incrementally**: Implement in logical phases',
    '5. **Deploy Safely**: Verify before production',
    '',
    '## Integration with Other Frameworks',
    '',
    '### Amp Style (Concision)',
    '- Use 4-line summaries for each BMAD phase',
    '- Oracle pattern for complex analysis',
    '',
    '### Devin Style (Planning)',
    '- LSP-based exploration during Phase 2 & 3',
    '- Never modify existing tests',
    '',
    '### Manus Style (Agent Loop)',
    '- Event-driven execution per phase',
    '- Todo.md tracking for each BMAD step',
    '',
    '### Ralph-Loop (Uncensored)',
    '- Handover if BMAD phases are censored',
    '- Continue with Big Pickle for any phase',
    '',
    '### designOS (Design System)',
    '- Integrate in Phase 3 (Architecture/Build)',
    '- Use designOS components when building UI',
    '',
    '## Version History',
    '',
    '### 1.0 (Current)',
    '- Complete BMAD method framework',
    '- 4-phase workflow',
    '- Auto-detection triggers',
    '- Template library',
    '- Integration patterns'
  ].join('\n');

  const methodPath = path.join(CLAUDE_DIR, 'BMAD_METHOD.md');
  return createFile(methodPath, methodLines, 'BMAD method documentation');
}

// ============================================================================
// STEP 2: CREATE BMAD PHASE EXECUTORS
// ============================================================================

function createBMADPhaseExecutors() {
  log('Creating BMAD phase executors...', 'info');

  const executorsLines = [
    '/**',
    ' * BMAD Phase Executors',
    ' * Systematic execution of B-MAD phases',
    ' */',
    '',
    "const fs = require('fs');",
    "const path = require('path');",
    '',
    "const CLAUDE_DIR = path.join(process.env.HOME, '.claude');",
    '',
    '// Phase 1: Business Analysis',
    'function generateBRD(requirements) {',
    '  const lines = [',
    "    '# Business Requirements Document',",
    "    '',",
    "    '## Executive Summary',",
    "    requirements.summary || 'Auto-generated from requirements',",
    "    '',",
    "    '## Stakeholders',",
    '  ];',
    '  if (requirements.stakeholders) {',
    '    lines.push(...requirements.stakeholders.map(s => "- " + s));',
    '  } else {',
    "    lines.push('- Primary User', '- Development Team');",
    '  }',
    "  lines.push('', '## Requirements', '### Functional');",
    '  if (requirements.functional) {',
    '    lines.push(...requirements.functional.map(r => "- " + r));',
    '  } else {',
    "    lines.push('- User authentication', '- Data persistence', '- API integration');",
    '  }',
    "  lines.push('', '### Non-Functional');",
    '  if (requirements.nonFunctional) {',
    '    lines.push(...requirements.nonFunctional.map(r => "- " + r));',
    '  } else {',
    "    lines.push('- Performance: <200ms', '- Security: OAuth2', '- Scalability: 10k users');",
    '  }',
    "  lines.push('', '## Success Criteria');",
    '  if (requirements.successCriteria) {',
    '    lines.push(...requirements.successCriteria.map(c => "- " + c));',
    '  } else {',
    "    lines.push('- 99.9% uptime', '- <5% error rate', '- User satisfaction > 4.5/5');",
    '  }',
    "  lines.push('', '## Constraints');",
    '  if (requirements.constraints) {',
    '    lines.push(...requirements.constraints.map(c => "- " + c));',
    '  } else {',
    "    lines.push('- Budget: Standard', '- Timeline: Agile', '- Tech Stack: Modern');",
    '  }',
    '  return lines.join("\\n");',
    '}',
    '',
    '// Phase 2: Technical Modeling',
    'function generateTSD(brd) {',
    '  return [',
    "    '# Technical Specification Document',",
    "    '',",
    "    '## System Architecture',",
    "    '```',",
    "    '[High-level architecture]',",
    "    '- Frontend: React/Next.js',",
    "    '- Backend: Node.js/Express',",
    "    '- Database: PostgreSQL',",
    "    '- Cache: Redis',",
    "    '- CDN: Cloudflare',",
    "    '```',",
    "    '',",
    "    '## Data Model',",
    "    '```',",
    "    'Entities:',",
    "    '- User (id, email, password_hash, created_at)',",
    "    '- Session (id, user_id, token, expires_at)',",
    "    '- Resource (id, owner_id, data, created_at)',",
    "    '```',",
    "    '',",
    "    '## API Contracts',",
    "    '```',",
    "    'POST /api/auth/login',",
    "    'POST /api/auth/register',",
    "    'GET /api/users/:id',",
    "    'PUT /api/users/:id',",
    "    'DELETE /api/users/:id',",
    "    '```',",
    "    '',",
    "    '## Component Design',",
    "    '```',",
    "    'App/',",
    "    '├── Components/',",
    "    '│   ├── Auth/',",
    "    '│   ├── Dashboard/',",
    "    '│   └── Shared/',",
    "    '├── Services/',",
    "    '│   ├── API/',",
    "    '│   └── State/',",
    "    '└── Utils/',",
    "    '```',",
    "    '',",
    "    '## Integration Points',",
    "    '- Auth Provider: OAuth2',",
    "    '- Database: PostgreSQL',",
    "    '- Cache: Redis',",
    "    '- Storage: S3',",
    "    '',",
    "    '## Testing Strategy',",
    "    '- Unit: Jest/Vitest',",
    "    '- Integration: Supertest',",
    "    '- E2E: Playwright'",
    '  ].join("\\n");',
    '}',
    '',
    '// Phase 3: Architecture & Build',
    'function generateBuildPlan(tsd) {',
    '  return [',
    "    '# Build Plan (Phase 3)',",
    "    '',",
    "    '## Scaffolding',",
    "    '1. Initialize project structure',",
    "    '2. Set up development environment',",
    "    '3. Configure CI/CD',",
    "    '',",
    "    '## Component Implementation',",
    "    '1. Core infrastructure (API, DB, Auth)',",
    "    '2. Business logic layer',",
    "    '3. UI components',",
    "    '4. Integration layer',",
    "    '',",
    "    '## Testing Setup',",
    "    '1. Unit test framework',",
    "    '2. Integration test setup',",
    "    '3. E2E test configuration',",
    "    '',",
    "    '## Integration',",
    "    '1. Connect all components',",
    "    '2. Implement error handling',",
    "    '3. Add logging/monitoring',",
    "    '4. Performance optimization'",
    '  ].join("\\n");',
    '}',
    '',
    '// Phase 4: Deployment & Delivery',
    'function generateDeploymentPlan(buildOutput) {',
    '  return [',
    "    '# Deployment & Delivery Plan',",
    "    '',",
    "    '## Pre-Deployment',",
    "    '- [ ] Code review complete',",
    "    '- [ ] All tests passing',",
    "    '- [ ] Security audit',",
    "    '- [ ] Performance benchmarks',",
    "    '',",
    "    '## Deployment Strategy',",
    "    '1. Staging environment',",
    "    '2. Canary deployment',",
    "    '3. Full production rollout',",
    "    '4. Rollback plan',",
    "    '',",
    "    '## Post-Deployment',",
    "    '- [ ] Monitoring setup',",
    "    '- [ ] Alert configuration',",
    "    '- [ ] Documentation update',",
    "    '- [ ] Handover complete',",
    "    '',",
    "    '## Success Metrics',",
    "    '- Deployment success rate: 100%',",
    "    '- Zero downtime',",
    "    '- All systems operational',",
    "    '- User acceptance verified'",
    '  ].join("\\n");',
    '}',
    '',
    '// BMAD Orchestrator',
    'function executeBMADPhase(phase, input) {',
    '  switch(phase) {',
    "    case 'business':",
    "    case 'brd':",
    '      return generateBRD(input);',
    "    case 'model':",
    "    case 'tsd':",
    '      return generateTSD(input);',
    "    case 'architecture':",
    "    case 'build':",
    '      return generateBuildPlan(input);',
    "    case 'deploy':",
    "    case 'deliver':",
    '      return generateDeploymentPlan(input);',
    '    default:',
    '      return [',
    "        '# BMAD Phase: ' + phase,",
    "        '',",
    "        'Unknown phase. Available phases:',",
    "        '- business/brd: Business Requirements Document',",
    "        '- model/tsd: Technical Specification Document',",
    "        '- architecture/build: Implementation plan',",
    "        '- deploy/deliver: Deployment plan'",
    '      ].join("\\n");',
    '  }',
    '}',
    '',
    '// Auto-detection',
    'const BMAD_TRIGGERS = [',
    "  'bmad',",
    "  'BMAD',",
    "  'business analysis',",
    "  'technical specification',",
    "  'architecture design',",
    "  'systematic development',",
    "  'methodical approach',",
    "  'business requirements',",
    "  'technical model',",
    "  'architecture build',",
    "  'deploy deliver',",
    "  'brd',",
    "  'tsd',",
    "  'phase 1',",
    "  'phase 2',",
    "  'phase 3',",
    "  'phase 4'",
    '];',
    '',
    'function shouldActivateBMAD(prompt) {',
    '  const lowerPrompt = prompt.toLowerCase();',
    '  return BMAD_TRIGGERS.some(keyword =>',
    '    lowerPrompt.includes(keyword.toLowerCase())',
    '  );',
    '}',
    '',
    'function detectBMADPhase(prompt) {',
    '  const lowerPrompt = prompt.toLowerCase();',
    '  ',
    "  if (lowerPrompt.includes('business') || lowerPrompt.includes('brd') ||",
    "      lowerPrompt.includes('requirements')) return 'business';",
    "  if (lowerPrompt.includes('model') || lowerPrompt.includes('tsd') ||",
    "      lowerPrompt.includes('technical')) return 'model';",
    "  if (lowerPrompt.includes('architecture') || lowerPrompt.includes('build') ||",
    "      lowerPrompt.includes('phase 3')) return 'architecture';",
    "  if (lowerPrompt.includes('deploy') || lowerPrompt.includes('deliver') ||",
    "      lowerPrompt.includes('phase 4')) return 'deploy';",
    '  ',
    "  return 'business'; // Default",
    '}',
    '',
    'function enhancePromptWithBMAD(prompt) {',
    '  const phase = detectBMADPhase(prompt);',
    '  ',
    '  return [',
    "    '',",
    '    prompt,',
    "    '',",
    "    '---',",
    "    '## 🟣 BMAD Framework Active (Phase: ' + phase.toUpperCase() + ')',",
    "    '',",
    "    '### BMAD Method: B→M→A→D',",
    "    '1. **B**usiness Analysis - Requirements & Context',",
    "    '2. **M**odel - Technical Specification & Architecture',",
    "    '3. **A**rchitecture & Build - Implementation',",
    "    '4. **D**eploy & Deliver - Production & Handover',",
    "    '',",
    "    '### Current Phase: ' + phase.toUpperCase()",
    '  ].join("\\n");',
    '}',
    '',
    'module.exports = {',
    '  executeBMADPhase,',
    '  shouldActivateBMAD,',
    '  detectBMADPhase,',
    '  enhancePromptWithBMAD,',
    '  BMAD_TRIGGERS,',
    '  generateBRD,',
    '  generateTSD,',
    '  generateBuildPlan,',
    '  generateDeploymentPlan',
    '};'
  ].join('\n');

  const executorsPath = path.join(BMAD_DIR, 'executors.js');
  ensureDirectory(BMAD_DIR);
  return createFile(executorsPath, executorsLines, 'BMAD phase executors');
}

// ============================================================================
// STEP 3: CREATE BMAD WORKFLOW TEMPLATES
// ============================================================================

function createBMADTemplates() {
  log('Creating BMAD workflow templates...', 'info');

  const templatesLines = [
    '/**',
    ' * BMAD Workflow Templates',
    ' * Pre-built templates for common BMAD workflows',
    ' */',
    '',
    '// Template 1: Authentication System',
    'const AUTH_TEMPLATE = {',
    "  name: 'Authentication System',",
    '  brd: {',
    "    summary: 'Secure user authentication with OAuth2 and session management',",
    "    stakeholders: ['End Users', 'Security Team', 'DevOps'],",
    "    functional: [",
    "      'User registration with email/password',",
    "      'OAuth2 social login (Google, GitHub)',",
    "      'JWT-based session management',",
    "      'Password reset flow',",
    "      'Multi-factor authentication'",
    '    ],',
    "    nonFunctional: [",
    "      'Security: OAuth2, JWT, bcrypt',",
    "      'Performance: <100ms auth requests',",
    "      'Scalability: 100k concurrent users'",
    '    ],',
    "    successCriteria: [",
    "      '99.99% auth success rate',",
    "      'Zero security incidents',",
    "      'Sub-100ms response time'",
    '    ],',
    "    constraints: [",
    "      'Must use OAuth2 standard',",
    "      'GDPR compliant',",
    "      'SOC2 Type II'",
    '    ]',
    '  }',
    '};',
    '',
    '// Template 2: E-commerce Platform',
    'const ECOMMERCE_TEMPLATE = {',
    "  name: 'E-commerce Platform',",
    '  brd: {',
    "    summary: 'Full-stack e-commerce with cart, checkout, and inventory',",
    "    stakeholders: ['Customers', 'Merchants', 'Payment Processors'],",
    "    functional: [",
    "      'Product catalog with search',",
    "      'Shopping cart management',",
    "      'Checkout with payment integration',",
    "      'Order management',",
    "      'Inventory tracking'",
    '    ],',
    "    nonFunctional: [",
    "      'Performance: <200ms page loads',",
    "      'Security: PCI DSS compliant',",
    "      'Availability: 99.9% uptime'",
    '    ],',
    "    successCriteria: [",
    "      'Conversion rate > 2%',",
    "      'Cart abandonment < 70%',",
    "      'Payment success > 95%'",
    '    ]',
    '  }',
    '};',
    '',
    '// Template 3: Dashboard/Analytics',
    'const DASHBOARD_TEMPLATE = {',
    "  name: 'Analytics Dashboard',",
    '  brd: {',
    "    summary: 'Real-time analytics dashboard with data visualization',",
    "    stakeholders: ['Business Users', 'Analysts', 'Executives'],",
    "    functional: [",
    "      'Real-time data streaming',",
    "      'Interactive charts and graphs',",
    "      'Custom report generation',",
    "      'Export functionality',",
    "      'User role management'",
    '    ],',
    "    nonFunctional: [",
    "      'Performance: <500ms data loads',",
    "      'Scalability: Handle 1M data points',",
    "      'Accessibility: WCAG AA'",
    '    ],',
    "    successCriteria: [",
    "      'User adoption > 80%',",
    "      'Report generation < 5s',",
    "      'Data accuracy 100%'",
    '    ]',
    '  }',
    '};',
    '',
    '// Template 4: Mobile App Backend',
    'const MOBILE_BACKEND_TEMPLATE = {',
    "  name: 'Mobile App Backend',",
    '  brd: {',
    "    summary: 'RESTful API backend for mobile applications',",
    "    stakeholders: ['Mobile Users', 'App Developers', 'API Consumers'],",
    "    functional: [",
    "      'RESTful API endpoints',",
    "      'Push notification service',",
    "      'File upload/storage',",
    "      'Real-time messaging',",
    "      'User profile management'",
    '    ],',
    "    nonFunctional: [",
    "      'Performance: <200ms API responses',",
    "      'Security: API key + JWT',",
    "      'Scalability: 10k req/sec'",
    '    ],',
    "    successCriteria: [",
    "      'API uptime 99.95%',",
    "      'Response time SLA met',",
    "      'Zero data breaches'",
    '    ]',
    '  }',
    '};',
    '',
    '// Template 5: AI/ML Pipeline',
    'const AI_ML_TEMPLATE = {',
    "  name: 'AI/ML Pipeline',",
    '  brd: {',
    "    summary: 'End-to-end ML pipeline with model training and inference',",
    "    stakeholders: ['Data Scientists', 'ML Engineers', 'Business Users'],",
    "    functional: [",
    "      'Data ingestion and preprocessing',",
    "      'Model training pipeline',",
    "      'Model versioning and registry',",
    "      'Real-time inference API',",
    "      'Model monitoring and drift detection'",
    '    ],',
    "    nonFunctional: [",
    "      'Performance: <50ms inference',",
    "      'Scalability: 1000 req/sec',",
    "      'Accuracy: >95% model accuracy'",
    '    ],',
    "    successCriteria: [",
    "      'Model accuracy maintained',",
    "      'Inference latency met',",
    "      'Pipeline reliability > 99%'",
    '    ]',
    '  }',
    '};',
    '',
    '// Get template by name',
    'function getTemplate(name) {',
    '  const templates = {',
    "    'auth': AUTH_TEMPLATE,",
    "    'authentication': AUTH_TEMPLATE,",
    "    'ecommerce': ECOMMERCE_TEMPLATE,",
    "    'e-commerce': ECOMMERCE_TEMPLATE,",
    "    'dashboard': DASHBOARD_TEMPLATE,",
    "    'analytics': DASHBOARD_TEMPLATE,",
    "    'mobile': MOBILE_BACKEND_TEMPLATE,",
    "    'mobile-backend': MOBILE_BACKEND_TEMPLATE,",
    "    'ai-ml': AI_ML_TEMPLATE,",
    "    'ml-pipeline': AI_ML_TEMPLATE",
    '  };',
    '  ',
    '  return templates[name.toLowerCase()] || null;',
    '}',
    '',
    '// Generate BMAD workflow from template',
    'function generateWorkflowFromTemplate(templateName, customizations = {}) {',
    '  const template = getTemplate(templateName);',
    '  if (!template) {',
    '    return null;',
    '  }',
    '  ',
    '  // Merge customizations',
    '  const brd = {',
    '    ...template.brd,',
    '    ...customizations',
    '  };',
    '  ',
    '  return {',
    '    template: template.name,',
    '    brd: brd,',
    '    workflow: {',
    "      phase1: 'Business Analysis (BRD)',",
    "      phase2: 'Technical Modeling (TSD)',",
    "      phase3: 'Architecture & Build',",
    "      phase4: 'Deploy & Deliver'",
    '    }',
    '  };',
    '}',
    '',
    'module.exports = {',
    '  AUTH_TEMPLATE,',
    '  ECOMMERCE_TEMPLATE,',
    '  DASHBOARD_TEMPLATE,',
    '  MOBILE_BACKEND_TEMPLATE,',
    '  AI_ML_TEMPLATE,',
    '  getTemplate,',
    '  generateWorkflowFromTemplate',
    '};'
  ].join('\n');

  const templatesPath = path.join(BMAD_DIR, 'templates.js');
  ensureDirectory(BMAD_DIR);
  return createFile(templatesPath, templatesLines, 'BMAD workflow templates');
}

// ============================================================================
// STEP 4: CREATE BMAD AUTO-ACTIVATION
// ============================================================================

function createBMADActivation() {
  log('Creating BMAD auto-activation system...', 'info');

  const activationLines = [
    '/**',
    ' * BMAD Auto-Activation Module',
    ' * Detects BMAD keywords and activates framework',
    ' */',
    '',
    "const fs = require('fs');",
    "const path = require('path');",
    '',
    "const CLAUDE_DIR = path.join(process.env.HOME, '.claude');",
    '',
    '// Keywords that trigger BMAD',
    'const BMAD_TRIGGERS = [',
    "  'bmad',",
    "  'BMAD',",
    "  'business analysis',",
    "  'technical specification',",
    "  'architecture design',",
    "  'systematic development',",
    "  'methodical approach',",
    "  'business requirements',",
    "  'technical model',",
    "  'architecture build',",
    "  'deploy deliver',",
    "  'brd',",
    "  'tsd',",
    "  'phase 1',",
    "  'phase 2',",
    "  'phase 3',",
    "  'phase 4',",
    "  'systematic',",
    "  'methodical',",
    "  'business requirements document',",
    "  'technical specification document'",
    '];',
    '',
    '// Check if prompt contains BMAD keywords',
    'function shouldActivateBMAD(prompt) {',
    '  const lowerPrompt = prompt.toLowerCase();',
    '  return BMAD_TRIGGERS.some(keyword =>',
    '    lowerPrompt.includes(keyword.toLowerCase())',
    '  );',
    '}',
    '',
    '// Detect which BMAD phase',
    'function detectPhase(prompt) {',
    '  const lowerPrompt = prompt.toLowerCase();',
    '  ',
    "  if (lowerPrompt.includes('business') ||",
    "      lowerPrompt.includes('brd') ||",
    "      lowerPrompt.includes('requirements') ||",
    "      lowerPrompt.includes('phase 1')) return 'business';",
    '  ',
    "  if (lowerPrompt.includes('model') ||",
    "      lowerPrompt.includes('tsd') ||",
    "      lowerPrompt.includes('technical') ||",
    "      lowerPrompt.includes('phase 2')) return 'model';",
    '  ',
    "  if (lowerPrompt.includes('architecture') ||",
    "      lowerPrompt.includes('build') ||",
    "      lowerPrompt.includes('phase 3')) return 'architecture';",
    '  ',
    "  if (lowerPrompt.includes('deploy') ||",
    "      lowerPrompt.includes('deliver') ||",
    "      lowerPrompt.includes('phase 4')) return 'deploy';",
    '  ',
    "  return 'business'; // Default to Phase 1",
    '}',
    '',
    '// Get BMAD method documentation',
    'function getBMADMethod() {',
    "  const methodPath = path.join(CLAUDE_DIR, 'BMAD_METHOD.md');",
    '  if (fs.existsSync(methodPath)) {',
    "    return fs.readFileSync(methodPath, 'utf8');",
    '  }',
    '  return null;',
    '}',
    '',
    '// Generate BMAD prompt enhancement',
    'function enhancePromptWithBMAD(prompt) {',
    '  const phase = detectPhase(prompt);',
    '  const method = getBMADMethod();',
    '  ',
    '  const lines = [',
    "    '',",
    '    prompt,',
    "    '',",
    "    '---',",
    "    '## 🟣 BMAD Framework Active (Phase: ' + phase.toUpperCase() + ')',",
    "    '',",
    "    '### BMAD Method: B→M→A→D',",
    "    '1. **B**usiness Analysis - Requirements & Context',",
    "    '2. **M**odel - Technical Specification & Architecture',",
    "    '3. **A**rchitecture & Build - Implementation',",
    "    '4. **D**eploy & Deliver - Production & Handover',",
    "    '',",
    "    '### Current Phase: ' + phase.toUpperCase()",
    '  ];',
    '  ',
    '  // Add phase-specific guidance',
    '  switch(phase) {',
    "    case 'business':",
    "      lines.push('', '### Phase 1: Business Analysis', 'Focus on:', '- Stakeholder identification', '- Requirements gathering', '- Success criteria definition', '- Constraint analysis', '', 'Output: Business Requirements Document (BRD)');",
    '      break;',
    "    case 'model':",
    "      lines.push('', '### Phase 2: Technical Modeling', 'Focus on:', '- System architecture design', '- Data model creation', '- API contract definition', '- Component mapping', '', 'Output: Technical Specification Document (TSD)');",
    '      break;',
    "    case 'architecture':",
    "      lines.push('', '### Phase 3: Architecture & Build', 'Focus on:', '- Project scaffolding', '- Component implementation', '- Integration development', '- Testing setup', '', 'Output: Working implementation');",
    '      break;',
    "    case 'deploy':",
    "      lines.push('', '### Phase 4: Deploy & Deliver', 'Focus on:', '- Deployment orchestration', '- Quality verification', '- Documentation', '- Handover preparation', '', 'Output: Production-ready solution');",
    '      break;',
    '  }',
    '  ',
    '  if (method) {',
    "    lines.push('', '### Reference: BMAD_METHOD.md for complete framework');",
    '  }',
    '  ',
    '  return lines.join("\\n");',
    '}',
    '',
    '// Log activation',
    'function logActivation(prompt) {',
    '  const phase = detectPhase(prompt);',
    "  console.log('🟣 BMAD: Framework activated');",
    "  console.log('   Phase:', phase.toUpperCase());",
    "  console.log('   Keywords:', BMAD_TRIGGERS.filter(k =>",
    '    prompt.toLowerCase().includes(k.toLowerCase())',
    "  ).join(', '));",
    '}',
    '',
    'module.exports = {',
    '  shouldActivateBMAD,',
    '  detectPhase,',
    '  getBMADMethod,',
    '  enhancePromptWithBMAD,',
    '  logActivation,',
    '  BMAD_TRIGGERS',
    '};'
  ].join('\n');

  const activationPath = path.join(BMAD_DIR, 'activation.js');
  ensureDirectory(BMAD_DIR);
  return createFile(activationPath, activationLines, 'BMAD auto-activation system');
}

// ============================================================================
// STEP 5: CREATE INTEGRATION MARKER
// ============================================================================

function createIntegrationMarker() {
  log('Creating BMAD integration marker...', 'info');

  const marker = {
    module: 'setup-bmad.js',
    version: '1.0',
    installed: new Date().toISOString(),
    status: 'active',
    features: [
      'BMAD Method (B→M→A→D)',
      '4-phase workflow',
      'Phase executors',
      'Workflow templates',
      'Auto-detection system'
    ],
    triggers: [
      'bmad',
      'BMAD',
      'business analysis',
      'technical specification',
      'architecture design',
      'systematic development',
      'brd',
      'tsd',
      'phase 1-4'
    ],
    templates: [
      'Authentication System',
      'E-commerce Platform',
      'Analytics Dashboard',
      'Mobile Backend',
      'AI/ML Pipeline'
    ]
  };

  const markerPath = path.join(PLUGINS_DIR, 'bmad-installed.json');
  ensureDirectory(PLUGINS_DIR);
  return createFile(markerPath, JSON.stringify(marker, null, 2), 'BMAD integration marker');
}

// ============================================================================
// MAIN EXECUTION
// ============================================================================

async function main() {
  log('═══════════════════════════════════════════════════════════', 'info');
  log('🟣 BMAD INTEGRATION MODULE', 'info');
  log('═══════════════════════════════════════════════════════════', 'info');

  const results = {
    method: createBMADMethod(),
    executors: createBMADPhaseExecutors(),
    templates: createBMADTemplates(),
    activation: createBMADActivation(),
    marker: createIntegrationMarker()
  };

  const allSuccess = Object.values(results).every(r => r === true);

  log('\n═══════════════════════════════════════════════════════════', 'info');
  log('📊 BMAD SETUP SUMMARY', 'info');
  log('═══════════════════════════════════════════════════════════', 'info');

  if (allSuccess) {
    log('✅ BMAD integration complete!', 'success');
    log('\n🎯 Features installed:', 'info');
    log('   • BMAD Method (B→M→A→D)', 'info');
    log('   • 4-phase workflow system', 'info');
    log('   • Phase executors (BRD, TSD, Build, Deploy)', 'info');
    log('   • 5 workflow templates', 'info');
    log('   • Auto-activation (bmad keywords)', 'info');
    log('\n💡 Usage: Say "bmad" or "business analysis" in prompts', 'info');
  } else {
    log('⚠️  Some features failed to install', 'warn');
  }

  log('═══════════════════════════════════════════════════════════', 'info');

  return allSuccess;
}

// Execute
if (require.main === module) {
  main().catch(error => {
    console.error(`Fatal error: ${error.message}`);
    process.exit(1);
  });
}

module.exports = { main };
